#!/usr/bin/env python3

if __name__ != '__main__':
    raise ImportError('This module is not for importing!')

import sys

import subprocess

with open('/dev/null', 'a') as dev_null:
    if subprocess.call(['which', 'gem'], stdout=dev_null, stderr=subprocess.STDOUT) != 0:
        sys.exit(2)

gem = subprocess.Popen(['gem', 'outdated'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
out, _ = gem.communicate()
out = out.decode('utf-8')
if gem.returncode == 0 and out != '':
    print('[ruby] Gem updates available. Install with `sudo gem update`. Outdated gems:')
    print(out[:-1] if out.endswith('\n') else out)
