#!/bin/sh

echo '[ ** ] releasing version' "$1" &&
git checkout --quiet -b release-"$1" &&
${EDITOR} README.md &&
printf '[....]\r' &&
git commit --all --message='Version bump' --quiet &&
printf '[....] merging into master\r' &&
git checkout --quiet master &&
git merge --quiet release-"$1" &&
printf '[=...] pushing master     \r' &&
git push --quiet &&
printf '[==..] merging into dev\r' &&
git checkout --quiet dev &&
git merge --quiet release-"$1" &&
printf '[===.] pushing dev     \r' &&
git push --quiet &&
printf '[====] deleting release branch\r' &&
git branch --quiet -d release-"$1" &&
printf '[ ok ] released               \n'
