# envars

# prepending to $PATH
PATH="/usr/texbin:${PATH}"
PATH="/usr/local/MacGPG2/bin:${PATH}"
PATH="/opt/X11/bin:${PATH}"
PATH="/sbin:${PATH}"
PATH="/usr/sbin:${PATH}"
PATH="/usr/local/sbin:${PATH}"
PATH="/bin:${PATH}"
PATH="/usr/bin:${PATH}"
PATH="/usr/local/bin:${PATH}"
PATH="/Applications/Alice.app/Contents/Resources/bin:${PATH}"
PATH="/usr/local/opt/ruby/bin:${PATH}"
PATH="/opt/local/sbin:${PATH}"
PATH="/opt/local/bin:${PATH}"
PATH="/opt/wurstmineberg/bin:${PATH}"
PATH="/opt/git/github.com/fenhl/syncbin/master:${PATH}"
PATH="/opt/hub/fenhl/syncbin:${PATH}"
PATH="${HOME}/git/github.com/fenhl/syncbin/master:${PATH}"
PATH="${HOME}/hub/fenhl/syncbin:${PATH}"
PATH="${HOME}/bin:${PATH}"
# appending to $PATH
PATH="${PATH}:/Library/Frameworks/Python.framework/Versions/3.5/bin"
PATH="${PATH}:/Library/Frameworks/Python.framework/Versions/3.4/bin"
PATH="${PATH}:/Library/Frameworks/Python.framework/Versions/3.3/bin"
PATH="${PATH}:/Library/Frameworks/Python.framework/Versions/2.7/bin"
export PATH

# locale settings
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

# default programs for editing and redirection
export EDITOR=nano
export VISUAL=nano

# git repos
if [[ -d /opt/git ]]; then
    export GITDIR=/opt/git
elif [[ -d ~/git ]]; then
    export GITDIR=${HOME}/git
fi

# Python modules and interactive mode config
if [[ -n ${PYTHONPATH} ]]; then
    export PYTHONPATH="/opt/py:${HOME}/py:/opt/git/github.com/fenhl/syncbin/master/python:${HOME}/git/github.com/fenhl/syncbin/master/python:/usr/lib/python3.5:/usr/lib/python3.4:/usr/lib/python3.3:${PYTHONPATH}"
else
    export PYTHONPATH="/opt/py:${HOME}/py:/opt/git/github.com/fenhl/syncbin/master/python:${HOME}/git/github.com/fenhl/syncbin/master/python:/usr/lib/python3.5:/usr/lib/python3.4:/usr/lib/python3.3"
fi
export PYTHONSTARTUP="${GITDIR}/github.com/fenhl/syncbin/master/config/pythonstartup.py"

# TeX and LaTeX config
export TEXINPUTS=".:~/Library/Application\ Support/Fenhl/tex:"

# add aliases from syncbin
if [[ -d /opt/git/github.com/fenhl/syncbin/master ]]; then
    . /opt/git/github.com/fenhl/syncbin/master/aliases bash
elif [[ -d ~/git/github.com/fenhl/syncbin/master ]]; then
    . ~/git/github.com/fenhl/syncbin/master/aliases bash
fi

# Fenhl short prompt, bash edition

function syncbin-prompt-user {
    if [[ $(whoami) == root ]]; then
        echo '#'
    elif [[ $(whoami) == fenhl ]]; then
        echo ' '
    else
        echo $(whoami | cut -c 1)
    fi
}

function syncbin-prompt-host {
    if hostname -f > /dev/null 2>&1; then
        if [[ $(hostname -f) == fenubookair.local ]] || $(which localhost > /dev/null 2>&1) && [[ $(localhost) == fenubookair ]]; then
            echo ' '
        else
            echo $(hostname -f | cut -c 1)
        fi
    else
        echo '?'
    fi
}

function syncbin-prompt-path {
    if [[ "$PWD" == "$HOME" ]]; then
        echo ' '
    elif [[ "$PWD" == '/' ]]; then
        echo '/'
    elif git branch > /dev/null 2>&1; then
        echo 'g'
    elif hg root > /dev/null 2>&1; then
        echo 'm'
    else
        echo '.'
    fi
}

function syncbin-prompt-shell {
    echo '$'
}

PS1="\$(if [[ \$? == 0 ]]; then echo \"[\[\033[1;37m\]\$(syncbin-prompt-user)\$(syncbin-prompt-host)\$(syncbin-prompt-path)\$(syncbin-prompt-shell)\[\033[m\]]\"; else echo \"\[\033[1;31m\][\[\033[1;37m\]\$(syncbin-prompt-user)\$(syncbin-prompt-host)\$(syncbin-prompt-path)\$(syncbin-prompt-shell)\[\033[1;31m\]]\"; fi)\[\e[0m\] "
PS2="bash> "

export CLICOLOR=1

export LANG=en_US.UTF-8
