# envars

# prepending to $PATH
PATH="/usr/texbin:${PATH}"
PATH="/usr/local/MacGPG2/bin:${PATH}"
PATH="/opt/X11/bin:${PATH}"
PATH="/sbin:${PATH}"
PATH="/usr/sbin:${PATH}"
Path="/usr/local/sbin:${PATH}"
PATH="/bin:${PATH}"
PATH="/usr/bin:${PATH}"
PATH="/usr/local/bin:${PATH}"
PATH="/Applications/Alice.app/Contents/Resources/bin:${PATH}"
PATH="/usr/local/opt/ruby/bin:${PATH}"
PATH="/opt/local/sbin:${PATH}"
PATH="/opt/local/bin:${PATH}"
PATH="/opt/wurstmineberg/bin:${PATH}"
PATH="/opt/hub/fenhl/syncbin:${PATH}"
PATH="${HOME}/hub/fenhl/syncbin:${PATH}"
PATH="${HOME}/bin:${PATH}"
# appending to $PATH
PATH="${PATH}:/Library/Frameworks/Python.framework/Versions/3.4/bin"
PATH="${PATH}:/Library/Frameworks/Python.framework/Versions/3.3/bin"
PATH="${PATH}:/Library/Frameworks/Python.framework/Versions/2.7/bin"
export PATH

# locale settings
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

# default programs for editing and redirection
export EDITOR=nano
export VISUAL=nano
export NULLCMD=':'
export READNULLCMD=less

# config for automatic mail-checks
if [[ -n ${MAILPATH} ]]; then
    export MAILPATH="/var/mail/fenhl:/home/fenhl/Maildir:${MAILPATH}"
else
    export MAILPATH="/var/mail/fenhl:/home/fenhl/Maildir"
fi
export MAILCHECK=60

# github repos
if [[ -d /opt/hub ]]; then
    export HUB=/opt/hub
elif [[ -d ~/hub ]]; then
    export HUB=${HOME}/hub
fi

# print at university
export CUPS_SERVER=print.coli.uni-saarland.de

# Python modules and interactive mode config
if [[ -n ${PYTHONPATH} ]]; then
    export PYTHONPATH="/opt/py:/opt/hub/fenhl/syncbin/python:${HOME}/hub/fenhl/syncbin/python:/usr/lib/python3.4:/usr/lib/python3.3:${PYTHONPATH}"
else
    export PYTHONPATH="/opt/py:/opt/hub/fenhl/syncbin/python:${HOME}/hub/fenhl/syncbin/python:/usr/lib/python3.4:/usr/lib/python3.3"
fi
export PYTHONSTARTUP="${HUB}/fenhl/syncbin/config/pythonstartup.py"

# TeX and LaTeX config
export TEXINPUTS=".:~/Library/Application\ Support/Fenhl/tex:"
