# don't show input while loading
stty -echo

printf '[....] loading oh-my-zsh\r'

if [[ -d /opt/hub/robbyrussell/oh-my-zsh ]]; then
    ZSH=/opt/hub/robbyrussell/oh-my-zsh
else
    ZSH=${HOME}/hub/robbyrussell/oh-my-zsh
fi
ZSH_THEME="fenhl"
DEFAULT_USER="fenhl"
DEFAULT_HOST="fenubookair.local"

# autoupdate
DISABLE_UPDATE_PROMPT=true
export UPDATE_ZSH_DAYS=1

CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_CORRECTION="true"
#DISABLE_UNTRACKED_FILES_DIRTY="true" # disable marking untracked files under VCS as dirty. This makes repository status check for large repositories much, much faster.

plugins=(autojump brew git mosh osx pip)

printf '[=...] updating omz     \r'

source $ZSH/oh-my-zsh.sh

printf '[==..] defining environment variables and aliases\r'

# ^S inserts sudo
insert_sudo () {
    zle beginning-of-line
    zle -U "sudo "
}
zle -N insert-sudo insert_sudo
bindkey "^S" insert-sudo

# access the online help, for brew
if which brew &> /dev/null; then
    unalias run-help
    autoload run-help
    HELPDIR=/usr/local/share/zsh/helpfiles
fi

# add aliases from syncbin
if [[ -d /opt/hub/fenhl/syncbin ]]; then
    . /opt/hub/fenhl/syncbin/aliases define
elif [[ -d ${HOME}/hub/fenhl/syncbin ]]; then
    . ${HOME}/hub/fenhl/syncbin/aliases define
fi

printf '[===.] running startup scripts: syncbin-hasinet  \r'

# startup scripts
if which syncbin-hasinet &> /dev/null; then
    syncbin-hasinet
    SYNCBINHASINET=$?
else
    SYNCBINHASINET=0
fi
if [[ $SYNCBINHASINET -eq 0 ]]; then
    printf '[===.] running startup scripts: apt-get-wrapper\r'
    if which apt-get-wrapper &> /dev/null; then
        apt-get-wrapper
    fi
    printf '[===.] running startup scripts: softwareupdate-wrapper\r'
    if which softwareupdate-wrapper &> /dev/null; then
        softwareupdate-wrapper
    fi
    printf '[===.] running startup scripts: brew                  \r'
    if which brew &> /dev/null; then
        brew update > /dev/null
        brew upgrade > /dev/null
    fi
    printf '[===.] running startup scripts: hub \r'
    if which hub &> /dev/null; then
        if [[ -d /opt/hub/fenhl/syncbin ]]; then
            cd /opt/hub/fenhl/syncbin &&
            hub pull > /dev/null &&
            cd - > /dev/null
        elif [[ -d ${HOME}/hub/fenhl/syncbin ]]; then
            cd ${HOME}/hub/fenhl/syncbin &&
            hub pull > /dev/null &&
            cd - > /dev/null
        fi
    fi
fi
printf '[===.] running startup scripts: zshrc\r'
if which zshrc &> /dev/null; then
    . zshrc
fi

printf '[====] starting zsh session   \r'

# reënable input
stty echo
